export enum MODALS_IDS {
  TOKENS = 'TOKENS',
  VAULTS = 'VAULTS',
  DEPOSIT = 'DEPOSIT',
  PLATFORM_VOTE = 'PLATFORM_VOTE',
  CHOOSE_VE = 'CHOOSE_VE',
  BOOST = 'BOOST',
  BRIBE = 'BRIBE',
  VOTE = 'VOTE',
  ACTIONS_HISTORY = 'ACTIONS_HISTORY',
  ACCOUNT = 'ACCOUNT',
  WALLET_CONNECT = 'WALLET_CONNECT',
  STRATEGIES = 'STRATEGIES',
  NETWORKS = 'NETWORKS',
  ROUTE = 'ROUTE',
  APY = 'APY'
}
