
export const PLATFORM : { [key:string]:string; } = {
  '0': 'Unknown',
  '1': 'Tetu',
  '2': 'Quick Swap',
  '3': 'Sushi Swap',
  '4': 'Wault Swap',
  '5': 'Iron Swap',
  '6': 'Cosmic Swap',
  '7': 'Curve',
  '8': 'Dino Swap',
  '9': 'Iron Lending',
  '10': 'Hermes',
  '11': 'Cafe Swap',
  '12': 'Tetu Swap',
  '13': 'Spooky Swap',
  '14': 'AAVE',
  '15': 'AAVE_MAI_BAL',
  '16': 'GEIST',
  '17': 'HARVEST',
  '18': 'SCREAM',
  '19': 'KLIMA',
  '20': 'VESQ',
  '21': 'QIDAO',
  '22': 'SUNFLOWER',
  '23': 'NACHO',
  '24': 'STRATEGY_SPLITTER',
  '25': 'TOMB',
  '26': 'TAROT',
  '27': 'BEETHOVEN',
  '28': 'IMPERMAX',
  '29': 'Tetu', // TETU_SF
  '30': 'ALPACA',
  '31': 'MARKET',
  '32': 'UNIVERSE',
  '33': 'MAI_BAL',
  '34': 'UMA',
  '35': 'SPHERE',
  '36': 'BALANCER',
  '37': 'OTTERCLAM',
  '38': 'MESH',
  '39': 'dFORCE',
  '40': 'DYSTOPIA',
  '41': 'CONE',
  '42': 'AURA',
  '43': 'COMPOUND',
  '44': '0VIX',
}
