export enum MAIN_ROUTES {
  EMPTY = '',
  MAIN = '/',
  INVEST = 'invest',
  VE = 've',
  DASHBOARD = 'dashboard',
  VAULT_VOTES = 'vault-votes',
  PLATFORM_VOTES = 'platform-votes',
  VAULT_INFO = 'vault-info',
  VAULT_INFO_ADDRESS = 'vault-info/:vaultAdr',
  STRATEGY_INFO = 'strategy-info',
  STRATEGY_INFO_ADDRESS = 'strategy-info/:strategyAdr',
  REWARDS = 'rewards',
  REWARDS_HISTORY = 'rewards-history',
  REWARDS_HISTORY_ADDRESS = 'rewards-history/:vaultAdr',
  BRIDGE = 'bridge',
  EARN = 'earn',
  VAULT = 'vault/:vault',
  TETU_QI = "tetuqi",
  TETU_MESH = "tetumesh",
  TETU_BAL = "tetubal"
}
